[package]
name = "compute-rust-auth"
version = "0.2.0"
authors = []
edition = "2018"

[profile.release]
debug = true

[dependencies]
nholuongut = "0.7.1"
hmac-sha256 = "0.1.7"
rand = "0.8.3"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
base64 = "0.13.0"
toml = "0.5.8"
jwt-simple = "0.9.3"